### ISSUE TITLE
Explicit loops significantly faster than array multiplications (even with SIMD)

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/pythran#807]
The code to try to reproduce this is here (with a Makefile to compile and do the benchmarking with perf): https://bitbucket.org/fluiddyn/fluidfft/src/master/bench/pythran_implicit_loop

The python code:

```python
import numpy as np

# pythran export myfunc(float64[][])
# pythran export myfunc(complex128[][])
# pythran export myfunc(float64[][][])
# pythran export myfunc(complex128[][][])

def myfunc(a):
    return (a**2 + a**3 + 2) / 5.


# pythran export myfunc_loops2d(float64[][])
# pythran export myfunc_loops2d(complex128[][])

def myfunc_loops2d(aa):
    n0, n1 = aa.shape
    result = np.empty_like(aa)
    for i0 in range(n0):
        for i1 in range(n1):
            a = aa[i0, i1]
            result[i0, i1] = myfunc(a)
    return result


# pythran export myfunc_loops3d(float64[][][])
# pythran export myfunc_loops3d(complex128[][][])

def myfunc_loops3d(aa):
    n0, n1, n2 = aa.shape
    result = np.empty_like(aa)
    for i0 in range(n0):
        for i1 in range(n1):
            for i2 in range(n2):
                a = aa[i0, i1, i2]
                result[i0, i1, i2] = myfunc(a)
    return result

```

On my computers, the implementations with explicit loops are significantly faster than the one with the array multiplications. I try to add the SIMD precompiler flag but it does not change anything.

```
$ make
[...]
$ make perf2d 
## default 2d (no loop)
python -m perf timeit -s \
  'from bench import myfunc_default as func, f2d as arr' 'func(arr)'
.....................
Mean +- std dev: 10.6 ms +- 0.0 ms
# default 2d (explicit loops)
python -m perf timeit -s \
  'from bench import myfunc_loops2d_default as func, f2d as arr' 'func(arr)'
.....................
Mean +- std dev: 5.39 ms +- 0.01 ms
# simd 2d (no loop)
python -m perf timeit -s \
  'from bench import myfunc_simd as func, f2d as arr' 'func(arr)'
.....................
Mean +- std dev: 10.7 ms +- 0.3 ms
# simd 2d (explicit loops)
python -m perf timeit -s \
  'from bench import myfunc_loops2d_simd as func, f2d as arr' 'func(arr)'
.....................
Mean +- std dev: 5.40 ms +- 0.01 ms
```

The instruction set of the cpu:
```
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm arat epb xsaveopt pln pts dtherm invpcid_single tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid
```

**Comment by serge-sans-paille** [comment]
@paugier which compiler are you using? Any relevant extra flags in your `.pythranrc` ? I fail to reproduce such differences...

**Comment by paugier** [comment]
These results were obtained with gcc (4.9 and today I get something similar with gcc 5.4.0).

The performance differences are smaller with clang, especially with SIMD.

I added comparisons between clang and gcc for the 2d and 3d cases here https://bitbucket.org/fluiddyn/fluidfft/src/master/bench/pythran_implicit_loop (files `results*d.txt`).

No particular extra flags in my `.pythranrc`, just `complex_hook = True`.

**Comment by serge-sans-paille** [comment]
> No particular extra flags in my .pythranrc, just complex_hook = True.

And if you set it to False ?

**Comment by paugier** [comment]
Complex computations are slower without `complex_hook`, and explicit loops are still faster.

You can compare:
- https://bitbucket.org/fluiddyn/fluidfft/src/default/bench/pythran_implicit_loop/results2d.txt
- https://bitbucket.org/fluiddyn/fluidfft/src/default/bench/pythran_implicit_loop/results2d_complex_hook_False.txt

```
[pythran]
complex_hook = False

# complex128

## With clang 5.0.0

$ make perf2d  # complex

### default 2d (no loop)
Mean +- std dev: 21.3 ms +- 1.1 ms

### default 2d (explicit loops)
Mean +- std dev: 7.76 ms +- 0.57 ms

### simd 2d (no loop)
Mean +- std dev: 19.4 ms +- 1.3 ms

### simd 2d (explicit loops)
Mean +- std dev: 7.50 ms +- 0.09 ms

## With gcc 5.4.0

$ make perf2d  # complex

### default 2d (no loop)
Mean +- std dev: 23.7 ms +- 1.1 ms

### default 2d (explicit loops)
Mean +- std dev: 14.8 ms +- 1.6 ms

### simd 2d (no loop)
Mean +- std dev: 241 ms +- 5 ms

### simd 2d (explicit loops)
Mean +- std dev: 128 ms +- 14 ms

```

**Comment by serge-sans-paille** [comment]
@paugier : #1030 should definitively close the issue... or so I hope! Can you confirm?

**Comment by ashwinvis** [comment]
The following are the results, in my laptop after a `sudo python -m perf system tune`.

### branch master (6f2a8f6)

```sh
# with gcc 8.2.1 (with an empty `~/.pythranrc`)
## default 2d (no loop)
Mean +- std dev: 18.3 ms +- 0.3 ms
# default 2d (explicit loops)
Mean +- std dev: 11.4 ms +- 0.0 ms
# simd 2d (no loop)
Mean +- std dev: 18.7 ms +- 0.2 ms
# simd 2d (explicit loops)
Mean +- std dev: 11.4 ms +- 0.1 ms

# with gcc 8.2.1 (with `complex_hook=True` inside `~/.pythranrc`)
## default 2d (no loop)
Mean +- std dev: 5.48 ms +- 0.49 ms
# default 2d (explicit loops)
Mean +- std dev: 4.50 ms +- 0.11 ms
# simd 2d (no loop)
Mean +- std dev: 5.20 ms +- 0.03 ms
# simd 2d (explicit loops)
Mean +- std dev: 4.33 ms +- 0.01 ms
```

### branch fix/complex-scalar-broadcast-perf (9d18ec6)

```sh
# with gcc 8.2.1 (with an empty `~/.pythranrc`)
$ make perf2d
## default 2d (no loop)
Mean +- std dev: 14.2 ms +- 0.2 ms
# default 2d (explicit loops)
Mean +- std dev: 10.9 ms +- 0.0 ms
# simd 2d (no loop)
Mean +- std dev: 14.2 ms +- 0.3 ms
# simd 2d (explicit loops)
Mean +- std dev: 10.9 ms +- 0.1 ms

# with gcc 8.2.1 (with `complex_hook=True` inside `~/.pythranrc`)
$ make perf2d
## default 2d (no loop)
Mean +- std dev: 6.07 ms +- 0.07 ms
# default 2d (explicit loops)
Mean +- std dev: 4.45 ms +- 0.14 ms
# simd 2d (no loop)
python -m perf timeit -s \
Mean +- std dev: 5.49 ms +- 0.14 ms
# simd 2d (explicit loops)
Mean +- std dev: 4.40 ms +- 0.15 ms

```

**Comment by ashwinvis** [comment]
It seems that there **is** some improvement using the **default options** and using numpy like broadcasting, from ~18ms to ~14ms. However the benchmarks also suggest it **is still ~ 20% to 40% slower** with explicit loops. It is maybe too early to close this issue?

**Comment by paugier** [comment]
Hi @serge-sans-paille 

For me with clang 6.0 it is much better now! Impressive! Thank you for your work on this issue and glad that you managed to make the transition towards xsimd.

# branch master
```
# simd 2d (no loop)
.....................
Mean +- std dev: 7.47 ms +- 0.02 ms
# simd 2d (explicit loops)
.....................
Mean +- std dev: 5.72 ms +- 0.03 ms
```

# branch fix/complex-scalar-broadcast-perf
```
# simd 2d (no loop)
.....................
Mean +- std dev: 5.54 ms +- 0.01 ms
# simd 2d (explicit loops)
.....................
Mean +- std dev: 5.72 ms +- 0.03 ms
```

**Comment by serge-sans-paille** [comment]
@paugier : thanks for the positive feedback. I just pushed an update in the same branch, on my laptop this leads to significant improvments with gcc, can you confirm?

**Comment by paugier** [comment]
I'm sorry but I cannot confirm. Your last commit does not change anything for me...

**Comment by serge-sans-paille** [comment]
On Tue, Oct 02, 2018 at 09:46:53AM -0700, Pierre Augier wrote:
> I'm sorry but I cannot confirm. Your last commit does not change anything for
> me...

That's surprising, because it does on my laptop. I'll run your benchmark
instead of mine tomorrow. Thanks for the feedback anyway!

**Comment by serge-sans-paille** [comment]
Only partially fixed by #1030, keeping this one open.

**Comment by paugier** [comment]
Unfortunately no. Still the same performance issue with gcc 6.3 on my desktop.

I'm going to try on another computer.

I'm also starting to think it could be an issue with our method of measurement (no idea why but...). @serge-sans-paille which benchmark do you use? How do you run it?

**Comment by ashwinvis** [comment]
For me the timings look awesome with gcc 8.2.1.

* without `complex_hook`
```
## default 2d (no loop)
.....................
Mean +- std dev: 8.14 ms +- 0.36 ms
# default 2d (explicit loops)
.....................
Mean +- std dev: 7.48 ms +- 0.29 ms
# simd 2d (no loop)
.....................
Mean +- std dev: 7.41 ms +- 0.29 ms
# simd 2d (explicit loops)
.....................
Mean +- std dev: 7.07 ms +- 0.34 ms
```

* with `complex_hook=True`
```
## default 2d (no loop)
.....................
Mean +- std dev: 4.71 ms +- 0.22 ms
# default 2d (explicit loops)
.....................
Mean +- std dev: 4.56 ms +- 0.15 ms
# simd 2d (no loop)
.....................
Mean +- std dev: 5.57 ms +- 0.17 ms
# simd 2d (explicit loops)
.....................
Mean +- std dev: 4.38 ms +- 0.18 ms
```

[compared to what I reported before](https://github.com/serge-sans-paille/pythran/issues/807#issuecomment-425854037).

I believe most of the performance gains are from the improvements to the `numpy.square` function as indicated by the `pythran -P` output:

```python
import numpy as __pythran_import_numpy
def myfunc(a):
    return (((__pythran_import_numpy.square(a) + (__pythran_import_numpy.square(a) * a)) + 2) / 5.0)
```

 I wonder if our test-case is SIMD-optimizable? Are our flags good enough?

```
$(name)_simd.so: $(name).py
	pythran -v $(name).py -march=native -DUSE_XSIMD -o $(name)_simd.so
```

**Comment by serge-sans-paille** [comment]
After a quick asm inspection, turns out pythran does not use XSIMD when mixing complex numpers and scalars, which is a performance bug. I'll fix that.

**Comment by serge-sans-paille** [comment]
Thanks @paugier and @ashwinvis for the promising timing. I fixed a vectorization issue in fix/more-complex-vectorize branch #1044. And it's blazing fast on my laptop now. Same on your setup? -DXSIMD on.

**Comment by paugier** [comment]
Yes, finally I confirm! It's fast!

## branch fix/more-complex-vectorize

### gcc 6.3

```
## default 2d (no loop)
Mean +- std dev: 10.6 ms +- 0.0 ms
# default 2d (explicit loops)
Mean +- std dev: 5.41 ms +- 0.01 ms

# simd 2d (no loop)
Mean +- std dev: 5.72 ms +- 0.01 ms  <- broadcasting is now (nearly) as fast as explicit loops!
# simd 2d (explicit loops)
Mean +- std dev: 5.46 ms +- 0.01 ms
```

### clang 6.0

Clang is still better for broadcasting, even without SIMD...

Strangely, with my setup, adding XSIMD slightly decreases the performance for clang. But it's a very small effect.

```
## default 2d (no loop)
Mean +- std dev: 5.56 ms +- 0.03 ms
# default 2d (explicit loops)
Mean +- std dev: 5.56 ms +- 0.02 ms

# simd 2d (no loop)
Mean +- std dev: 5.66 ms +- 0.01 ms
# simd 2d (explicit loops)
Mean +- std dev: 5.73 ms +- 0.04 ms
```

**Comment by ashwinvis** [comment]
Noticeable improvement with SIMD here as well, with gcc 8.2.1!

* no `complex_hook`:

```sh

## default 2d (no loop)
Mean +- std dev: 8.09 ms +- 0.29 ms
# default 2d (explicit loops)
Mean +- std dev: 7.49 ms +- 0.29 ms
# simd 2d (no loop)
Mean +- std dev: 5.46 ms +- 0.09 ms <-------- BIG WIN!
# simd 2d (explicit loops)
Mean +- std dev: 7.09 ms +- 0.19 ms
```

* with `complex_hook`
```sh
## default 2d (no loop)
Mean +- std dev: 4.68 ms +- 0.14 ms
# default 2d (explicit loops)
Mean +- std dev: 4.58 ms +- 0.28 ms
# simd 2d (no loop)
Mean +- std dev: 5.46 ms +- 0.06 ms <-------- Seems like complex_hook is not applied
# simd 2d (explicit loops)
Mean +- std dev: 4.37 ms +- 0.20 ms
```
Seems like the original issue is resolved now. :confetti_ball: 

As a side note @paugier, it might be worthwhile to compare the actual gcc commands executed. I will share mine for the :

```sh
# Compile
C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fstack-protector-strong -fno-plt -flto=4 -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -march=x86-64 -mtune=generic -O3 -pipe -fstack-protector-strong -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fstack-protector-strong -fno-plt -fPIC
extra options: '-std=c++11 -fno-math-errno -w -fvisibility=hidden -fno-wrapv -std=c++11 -fno-math-errno -w -fvisibility=hidden -fno-wrapv -march=native'

# Link
g++ -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=4 -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now /tmp/tmp8oauit2o/tmp/tmpzrr1q89p.o -L/usr/lib64 -L/usr/lib64 -L/usr/lib -lcblas -lblas -lcblas -lblas -lpython3.7m -o /tmp/tmp4hj37o9c/mymod_simd.cpython-37m-x86_64-linux-gnu.so -fvisibility=hidden -Wl,-strip-all -fvisibility=hidden -Wl,-strip-all -march=native
```

**Comment by serge-sans-paille** [comment]
Great, let's close this issue then, now that #1044 is merged.
