### ISSUE TITLE
"Invalid call to pythranized function" on valid call

### ISSUE THREAD

**Issue by Dapid** [serge-sans-paille/pythran#842]
I have defined a function and annotated it as:
```
# pythran export compute_FN(float64[:, :], int, int8)
# pythran export compute_FN(float[:, :], int, int8)
```
When calling it, I get:

```
TypeError: Invalid call to pythranized function `compute_FN(ndarray, int, int8)'
Candidates are:
   compute_FN(float[][],int,int8)
   compute_FN(float[][].T,int,int8)
   compute_FN(float64[][],int,int8)
   compute_FN(float64[][].T,int,int8)
```

The array is of shape (480, 480), and dtype is float64. Strangely, when I cut the function out to provide an example, it works.

Any idea what is going on here? Any tips to debug? Is my annotation wrong?

**Comment by Dapid** [comment]
That didn't work. Neither does making an explicit copy.

The mJ array comes from scipy.linalg

 ```
    print(mJ.strides)
    print(mJ.flags)
    print()

    mJ = mJ.copy()

    print(mJ.strides)
    print(mJ.flags)
    print()
```

Gives:

```
(8, 20800)
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


(20800, 8)
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
```

Copy or not, it fails with:
```
TypeError: Invalid call to pythranized function `compute_FN(ndarray, int, int8)'
Candidates are:
   compute_FN(float[::][::],int,int8)
   compute_FN(float[][].T,int,int8)
   compute_FN(float64[::][::],int,int8)
   compute_FN(float64[][].T,int,int8)
   compute_FN(float[][],int,int8)
   compute_FN(float[][].T,int,int8)
   compute_FN(float64[][],int,int8)
   compute_FN(float64[][].T,int,int8)
```

**Comment by serge-sans-paille** [comment]
I fail to reproduce... even when getting the function input with same falgs are yours; Are you on master?

**Comment by Dapid** [comment]
I am on master, yes. The strange thing is that it only fails when running as a part of the big program, not when I isolate it.

Is there any way I can make the error message more verbose?

**Comment by Dapid** [comment]
You can find the full example here:

https://github.com/ElofssonLab/pyGaussDCA/tree/

Go to src and run _test.py. It fails on Pythran master.

**Comment by Dapid** [comment]
So, it seems I managed to mess up the example. Here it is now, failing as before:

https://github.com/ElofssonLab/pyGaussDCA/tree/invalid_call/gaussdca/test

**Comment by Dapid** [comment]
Investigating the strides with the [ugly patch](https://github.com/serge-sans-paille/pythran/issues/853#issuecomment-391778834) I get:

```1  8480  8
  8480   8   1060 <----
  8   8480   1060
1  8480  8
  8480   8   1060 <----
  8   8480   1060
```
So it is expecting strides in the opposite direction. The relevant declarations are:

```
# pythran export compute_FN(float64[:, :], int, int8)
# pythran export compute_FN(float64[::, :], int, int8)
```

And the options:
```
   compute_FN(float64[::,::],int,int8)
   compute_FN(float64[:,:].T,int,int8)
   compute_FN(float64[:,:],int,int8)
   compute_FN(float64[:,:].T,int,int8)
```
So, are they perhaps the declarations not being parsed properly by Pythran? Maybe when the prettyprinter is finished it can shed more light on this.

**Comment by serge-sans-paille** [comment]
@Dapid I fixed an issue with the ``float64[::,::]`` notation in 2277853430de9d35b6cc5b24e1039304664c55b3 , there is a chance it fixes your issue too.

**Comment by h-vetinari** [comment]
This does not seem fully fixed, unfortunately...

I'm on the latest available commit from master (https://github.com/serge-sans-paille/pythran/commit/bb977467e42a36d393df6bad4d3a459d86defbb9), Windows 10, Python 3.6.6, MSVC 2017 Community 15.8.2, IPython 6.5.0, and I get the same errors no matter what I've tried:

```
%%pythran
#pythran export myfunc(float[][])
#pythran export myfunc(float[::,:])
import numpy as np

def myfunc(x):
    numtriangles = x.shape[0]
    res = np.ones((numtriangles, 2), dtype=float)
    for i in range(numtriangles):
        # toy example; actually more complicated...
        res[i, 0] = x[i, :].min()
        res[i, 1] = x[i, :].max()
    return res
```

compiles without problems, but then:

```
import pandas as pd 
import numpy as np
N = 20
df = pd.DataFrame(np.random.randint(1e3, 2e3, (N, 3)), columns=['x1', 'x2', 'x3'])
x = df.values
myfunc(x.copy())  # same error for myfunc(x)
# TypeError: Invalid call to pythranized function `myfunc(ndarray)'
# Candidates are:
#     - myfunc(float[::,::])
#     - myfunc(float[:,:])
```

**Comment by serge-sans-paille** [comment]
ok, as suggested by @Dapid a while ago, I'll improve the pretty printer so that we now why this type is not accepted. ndarray is not sufficient :-)

**Comment by h-vetinari** [comment]
@serge-sans-paille 
That's great! I deleted my previous comment because I had an embarassing error in there (int vs float), but the problem persists for copy vs. no-copy, and in another case, I still haven't gotten it to work at all. (same for the "ugly patch" from @Dapid, so still don't know why).
